[package]
name = "k8s"
version = "0.1.0"
authors = ["Johannes Dato <j.dato@dr-flex.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "0.7.19"
rand = "0.7.3"